# Generated by Django 6.0.2 on 2026-02-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Time')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.IntegerField(default=0, verbose_name='Gols do Time da Casa')),
                ('gols_visitante', models.IntegerField(default=0, verbose_name='Gols do Time Visitante')),
                ('data_jogo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Jogo')),
                ('realizado', models.BooleanField(default=True, verbose_name='Jogo Realizado?')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_casa', to='core.time', verbose_name='Time da Casa')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_visitante', to='core.time', verbose_name='Time Visitante')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['-data_jogo'],
            },
        ),
    ]
