# Generated by Django 6.0.2 on 2026-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['data_jogo'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AddField(
            model_name='jogo',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local do Jogo'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='data_jogo',
            field=models.DateTimeField(verbose_name='Data do Jogo'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='Jogo Realizado?'),
        ),
    ]
