# Generated by Django 5.2.1 on 2026-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jogo_options_jogo_local_alter_jogo_data_jogo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['rodada', 'data_jogo'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AddField(
            model_name='jogo',
            name='rodada',
            field=models.IntegerField(default=1, verbose_name='Rodada'),
        ),
    ]
