# Generated by Django 5.2.1 on 2026-02-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_jogo_options_jogo_rodada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Jogador')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número da Camisa')),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('VOL', 'Volante'), ('MEI', 'Meio-campo'), ('ATA', 'Atacante'), ('TEC', 'Técnico')], max_length=3, verbose_name='Posição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jogadores/', verbose_name='Foto')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(default='Brasileiro', max_length=50, verbose_name='Nacionalidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['time', 'posicao', 'numero'],
            },
        ),
    ]
