# Generated by Django 5.2.1 on 2026-02-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jogador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['-data_jogo'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField(verbose_name='Minuto do Gol')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('PENALTI', 'Pênalti'), ('FALTA', 'Falta'), ('CONTRA', 'Contra')], default='NORMAL', max_length=10, verbose_name='Tipo de Gol')),
                ('contra', models.BooleanField(default=False, verbose_name='Gol Contra?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='core.jogador', verbose_name='Jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='core.jogo', verbose_name='Jogo')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Gols',
                'ordering': ['jogo', 'minuto'],
            },
        ),
    ]
